name: OWASP Dependency-Check (SCA)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    name: Scan Python dependencies using OWASP Dependency-Check

    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare reports folder
        run: mkdir -p ${{ github.workspace }}/reports

      - name: Run OWASP Dependency-Check via Docker
        run: |
          docker run --rm \
            -e NVD_API_KEY=$NVD_API_KEY \
            -v ${{ github.workspace }}:/src \
            -v ${{ github.workspace }}/reports:/src/reports \
            owasp/dependency-check \
            --project "FlaskApp" \
            --scan /src \
            --format "HTML" \
            --out /src/reports \
            --disableAssembly
