name: OWASP Dependency-Check (SCA)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    name: Run OWASP Dependency-Check CLI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download OWASP Dependency-Check CLI
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check-8.4.0-release.zip -d dependency-check

      - name: Run OWASP Dependency-Check
        run: |
          mkdir -p reports
          bash dependency-check/dependency-check/bin/dependency-check.sh \
            --project "FlaskApp" \
            --scan ./ \
            --out reports \
            --format HTML \
            --disableAssembly
      - name: Print OWASP Dependency-Check Summary to Console
        run: |
          echo "================ Dependency-Check Summary ================"
          grep -i "CVE-" reports/dependency-check-report.html || echo "No CVEs found."
          echo "=========================================================="